27 create verification page
GTBitsOfGood/npp pull request #61
Opened 2020-10-31 21:46 UTC by mariashapiro

Fixes issue #27

2020-10-31 21:50 UTC, mariashapiro commented
Need to update a couple of things that are different in the low fidelity figma

2020-10-31 22:13 UTC, Josh-McFarlin approved these changes

2020-11-02 19:16 UTC, chrisjobando requested changes
Needs to have a corresponding page to be in route

2020-11-03 01:44 UTC, chrisjobando approved these changes

2020-11-05 02:21 UTC, merged